"""Downstream consumer of the warehouse — emits a markdown spend report.

This is the REAL consumer the dbt exposure `monthly_spend_report` points at, so the
lineage graph ends in an actual use, not a stub. Reads the marts (read-only) and
writes reports/monthly_spend_summary.md with real numbers.

Usage:  python scripts/report.py
"""
from __future__ import annotations

from pathlib import Path

import duckdb

DB = "finance_warehouse.duckdb"
OUT = Path("reports/monthly_spend_summary.md")


def main() -> None:
    con = duckdb.connect(DB, read_only=True)

    months = con.execute(
        "select count(distinct month) from mart_monthly_account_spend"
    ).fetchone()[0]

    accounts = con.execute("""
        select a.account_name, a.account_type,
               round(sum(m.total_outflow), 2) as outflow,
               round(sum(m.total_inflow), 2)  as inflow,
               round(sum(m.net_amount), 2)    as net,
               sum(m.txn_count)               as txns
        from mart_monthly_account_spend m
        join dim_account a on m.account_key = a.account_key
        group by 1, 2
        order by outflow desc
    """).fetchall()

    categories = con.execute("""
        select dm.category_primary, round(sum(f.abs_amount), 2) as spend
        from fct_transactions f
        join dim_merchant dm on f.merchant_key = dm.merchant_key
        where not f.is_inflow
        group by 1
        order by spend desc
        limit 6
    """).fetchall()
    con.close()

    lines = [
        "# Monthly Account-Spend Report",
        "",
        "> Generated by `scripts/report.py` from `mart_monthly_account_spend` + the dims — the",
        "> downstream consumer named by the dbt exposure `monthly_spend_report`. Numbers are real",
        f"> outputs of the warehouse over **{months} months**.",
        "",
        "## Spend by account",
        "",
        "| Account | Type | Outflow | Inflow | Net | Txns |",
        "|---|---|--:|--:|--:|--:|",
    ]
    for name, typ, out, inf, net, txns in accounts:
        lines.append(f"| {name} | {typ} | ${out:,.2f} | ${inf:,.2f} | ${net:,.2f} | {txns:,} |")

    lines += ["", "## Top spend categories (outflow)", "", "| Category | Spend |", "|---|--:|"]
    for cat, spend in categories:
        lines.append(f"| {cat} | ${spend:,.2f} |")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(accounts)} accounts, {len(categories)} categories, {months} months)")


if __name__ == "__main__":
    main()
